async def ListCommands(message):
  # Generate message that lists all commands, split into 2 messages due to character limit
  CommandsMessage1 = "**The following commands are available (all times must be provided in UTC time for the bot to function properly):**\n**!Create**, used to create a run example use without template:\n!Create TestRaid !DateTime 01-08-2021 19:00 !NrOfPlayers 24 !NrOfTanks 3 !NrOfDps 15 !NrOfHealers 6 !Role Tank\nExample use with template:\n!Create TestRaid !DateTime 01-08-2021 19:00 !Template Raid !Role Tank\n**!Join**, used to sign yourself up for a run example use: !Join TestRaid !DateTime 01-08-2021 19:00 !Role Tank\n**!Withdraw**, used to remove yourself from a run example use: !Withdraw TestRaid !DateTime 01-08-2021 19:00\n**!Cancel**, used to cancel a run example use: !Cancel TestRaid !DateTime 01-08-2021 19:00 (only the organizer of the run is allowed to cancel)\n**!Info**, used to retrieve info for a specific run example use: !Info TestRaid !DateTime 01-08-2021 19:00\n**!Runs**, used to retrieve all runs planned on a specific date example use: !Runs 01-08-2021\n**!Reschedule**, used to reschedule the run to another date example use: !Reschedule TestRaid !DateTime 04-08-2021 19:00 !NewDateTime 10-08-2021 19:00 (only the organizer of the run is allowed to reschedule)\n**!ChangeRole**, used to change the role you signed up as for the run example use: !ChangeRole TestRaid !DateTime 01-08-2021 19:00 !Role Tank\n**!Templates**, lists all available templates that can be used to create a run with example use: !Templates\n**!Commands**, lists all supported commands example use: !Commands\n**!Roles**, lists all available roles example use: !Roles\n"
  
  CommandsMessage2 = "**!Rally**, used to tag all signed up members to a run example use: !Rally TestRaid !DateTime 04-08-2021 19:00 (this command only works from 1 hour before the start time of the run until the start time)\n**Dismiss**, used to dismiss a member from the run example use: !Dismiss TestRaid DateTime 04-08-2021 19:00 !User UserName (only the organizer of the run is allowed to dismiss members)\n**!AddDefaultTemplates**, used to add some default templates for FFXIV example use: !AddDefaultTemplates\n**!AddTemplate**, used to create a custom template example use: !AddTemplate TestTemplate !NrOfPlayers 8 !NrOfTanks 2 !NrOfDps 4 !NrOfHealers 2\n**!UpdateTemplate**, used to update an existing template example use: !UpdateTemplate TestTemplate !NrOfPlayers 8 !NrOfTanks 2 !NrOfDps 4 !NrOfHealers 2 (only the creator of the template is allowed to update)\n**!DeleteTemplate**, used to delete a template example use: !DeleteTemplate TestTemplate (only the creator of the template is allowed to delete)"

  # Post message in channel command was called from
  await message.channel.send(CommandsMessage1)
  await message.channel.send(CommandsMessage2)
  return